Repository ibexa/graphql, pull requests merged in 2022-02, with the labels that each got.

#21 IBX-1696: Rebranded Container parameters and Config Resolver namespaces
  doc/howto/custom_field_type.md
  src/bundle/DependencyInjection/IbexaGraphQLExtension.php
  src/bundle/Resources/config/default_settings.yaml
  src/bundle/Resources/config/services/schema.yaml
  src/bundle/Resources/config/services/services.yaml
  src/lib/Resolver/SiteaccessGuesser/SiteaccessGuesser.php
Labels: Feature

#26 IBX-1993: Upgrade overblog/graphql-bundle to v0.14
  composer.json
  spec/Schema/Domain/Content/NameHelperSpec.php
  spec/Schema/Domain/Content/Worker/ContentType/AddItemOfTypeConnectionToGroupSpec.php
  src/bundle/Resources/config/graphql/DomainContent.types.yaml
  src/bundle/Resources/config/graphql/Item.types.yaml
  src/lib/Schema/Builder/Input/Type.php
  src/lib/Schema/Builder/SchemaBuilder.php
  src/lib/Schema/Domain/Content/Worker/ContentType/DefineItemConnection.php
Labels: Improvement, QA approved, Ready for review

#30 IBX-2424: Fixed deprecation leftovers after upgrading `overblog/graphql` to v0.14
  composer.json
  src/lib/Relay/DomainConnectionBuilder.php
  src/lib/Relay/PageAwareConnection.php
  src/lib/Relay/SearchResolver.php
Labels: Bug, Ready for review
